<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <BaseIntermediateOutputPath>$(SolutionDir)obj\</BaseIntermediateOutputPath>
        <BaseOutputPath>$(SolutionDir)..\bin\</BaseOutputPath>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
</Project>
